// Auto-generated by scripts/fetch-trek-photos.ts — REAL, commercial-safe CC
// photos of each trek (Openverse: Flickr + Wikimedia Commons), with attribution.
// Reviewed for relevance. Treks absent here have no real photos available and
// show no step images (never a representative stand-in).
import type { TrekPhoto } from "@/lib/trek/schema";

export const TREK_PHOTOS: Record<string, TrekPhoto[]> = {
  "chandrashila-tungnath": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/20/Chandrashila%2Cuttarakhand_-_panoramio.jpg",
      "title": "Chandrashila,uttarakhand - panoramio",
      "credit": "Biswajit Majumdar",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=58507639"
    },
    {
      "url": "https://live.staticflickr.com/7445/10898332344_37a45bfc7c_b.jpg",
      "title": "Kedarnath",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/10898332344"
    },
    {
      "url": "https://live.staticflickr.com/7424/10898468473_cc165613e3_b.jpg",
      "title": "Gateway to Tungnath Trail @ Chopta",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/10898468473"
    },
    {
      "url": "https://live.staticflickr.com/7333/10898527204_a7dfea0466_b.jpg",
      "title": "Kedarnath and Kedar Dome",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/10898527204"
    },
    {
      "url": "https://live.staticflickr.com/7439/10898697343_f5e4e87d08_b.jpg",
      "title": "Nanda Devi - Hidden Summit",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/10898697343"
    },
    {
      "url": "https://live.staticflickr.com/2023/2279353126_80cf74ebb6_b.jpg",
      "title": "DSC01558",
      "credit": "clara & james",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/63709829@N00/2279353126"
    }
  ],
  "deoria-tal": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/19/Deoria_Tal_Chandrashila_Chaukamba_reflection.jpg",
      "title": "Deoria Tal Chandrashila Chaukamba reflection",
      "credit": "Senthilnath G T, XS. Gtsenthilnath at English Wikipedia",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=32754152"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/40/Birds_at_Deoria_Tal%2C_Himalaya.jpg",
      "title": "Birds at Deoria Tal, Himalaya",
      "credit": "Engineercad",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49777955"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Fire-frontedSerin_at_Deoria_Tal.jpg",
      "title": "Fire-frontedSerin at Deoria Tal",
      "credit": "AJIT HOTA",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=58410938"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/12/Himalayan_peak_Kedarnath_%2CChaukhamaba_and_others_from_Deoria_Tal.jpg",
      "title": "Himalayan peak Kedarnath ,Chaukhamaba and others from Deoria Tal",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=42340408"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/78/Fire-fronted_serin_at_Deoria_Tal.jpg",
      "title": "Fire-fronted serin at Deoria Tal",
      "credit": "AJIT HOTA",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=58410502"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/94/Deoria_Tal.jpg",
      "title": "Deoria Tal",
      "credit": "Mudassarmunshi",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49423112"
    }
  ],
  "pin-parvati-pass": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/6/65/Pin_Parvati_from_Sarpass.jpg",
      "title": "Pin Parvati from Sarpass",
      "credit": "KP2385",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49527527"
    }
  ],
  "dhankar-lake": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Manirang_peak_from_Dhankar_Lake_Spiti_Himachal_Pradesh_India.jpg",
      "title": "Manirang peak from Dhankar Lake Spiti Himachal Pradesh India",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49731327"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Dhankar_lake_at_Dhankar_in_Spiti_valley_Himachal_Pradesh_photography_by_Sumita_Roy.jpg",
      "title": "Dhankar lake at Dhankar in Spiti valley Himachal Pradesh photography by Sumita Roy",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=42917547"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/72/Dhankar_lake_by_Sumita_Roy_Dutta.jpg",
      "title": "Dhankar lake by Sumita Roy Dutta",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=53901339"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Dhankar_lake.jpg",
      "title": "Dhankar lake",
      "credit": "Ayepee99",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=64989242"
    },
    {
      "url": "https://live.staticflickr.com/5207/5338033777_7a770690d3_b.jpg",
      "title": "Lake Dhankar",
      "credit": "njyo",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/53908695@N00/5338033777"
    },
    {
      "url": "https://live.staticflickr.com/115/293348395_416d830e17_b.jpg",
      "title": "BathAt4000",
      "credit": "4ocima",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/19016430@N00/293348395"
    }
  ],
  "kanamo-peak": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/d2/Kanamo_Peaks_South_Kibber_Spiti_Jun18_D72_7523.jpg",
      "title": "Kanamo Peaks South Kibber Spiti Jun18 D72 7523",
      "credit": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=122327508"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/84/Kanamo_Peaks_Southwest_Kibber_Spiti_Jun18_D72_7743.jpg",
      "title": "Kanamo Peaks Southwest Kibber Spiti Jun18 D72 7743",
      "credit": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=122327492"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/50/Kanamo_Peak_South_Kibber_Spiti_Jun18_D72_7534.jpg",
      "title": "Kanamo Peak South Kibber Spiti Jun18 D72 7534",
      "credit": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=122327609"
    }
  ],
  "hampta-pass": [
    {
      "url": "https://live.staticflickr.com/2901/14019693062_94d6823b35_b.jpg",
      "title": "Hampta Pass Trek",
      "credit": "theglobalpanorama",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/121483302@N02/14019693062"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/79/Shepherd_on_the_way_to_Hampta_Pass.jpg",
      "title": "Shepherd on the way to Hampta Pass",
      "credit": "Raja Selvaraj",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=11761402"
    },
    {
      "url": "https://live.staticflickr.com/4124/5051940168_749f045e6d_b.jpg",
      "title": "All set to conquer Hampta Pass",
      "credit": "Raja12",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/16764009@N00/5051940168"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Mesmerising_beauty_of_Hampta_pass_on_Chandrataal_Trek_Himachal_India.jpg",
      "title": "Mesmerising beauty of Hampta pass on Chandrataal Trek Himachal India",
      "credit": "Photos Worldwide",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104541860"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/77/Hampta_Pass_Himachal_Pradesh_India.jpg",
      "title": "Hampta Pass Himachal Pradesh India",
      "credit": "Raja Selvaraj",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=11761451"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Hampta_Pass_-_panoramio.jpg",
      "title": "Hampta Pass - panoramio",
      "credit": "mkasiak",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=47810882"
    }
  ],
  "bhrigu-lake": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Bhrigu_lake_Kullu.JPG",
      "title": "Bhrigu lake Kullu",
      "credit": "Kartik.a.rokde",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=33439822"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/7a/Bhrigu_Lake_by_Ahmad_Faiz_Mustafa_%284%29.jpg",
      "title": "Bhrigu Lake by Ahmad Faiz Mustafa (4)",
      "credit": "In Transit",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=174307711"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/01/Bhrigu_Lake_by_Ahmad_Faiz_Mustafa_%281%29.jpg",
      "title": "Bhrigu Lake by Ahmad Faiz Mustafa (1)",
      "credit": "In Transit",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=174307706"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Bhrigu_Lake_by_Ahmad_Faiz_Mustafa_%283%29.jpg",
      "title": "Bhrigu Lake by Ahmad Faiz Mustafa (3)",
      "credit": "In Transit",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=174307705"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/06/Bhrigu_Lake_by_Ahmad_Faiz_Mustafa_%282%29.jpg",
      "title": "Bhrigu Lake by Ahmad Faiz Mustafa (2)",
      "credit": "In Transit",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=174307702"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/d8/Manali_India.jpg",
      "title": "Manali India",
      "credit": "sahil",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=8472009"
    }
  ],
  "beas-kund": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/93/Jaswanth_Raj_Visited_Beas_Kund.jpg",
      "title": "Jaswanth Raj Visited Beas Kund",
      "credit": "GovinduGari",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=157378032"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/53/Unknown_graves%2C_Beas_Kund_%2801%29.jpg",
      "title": "Unknown graves, Beas Kund (01)",
      "credit": "Moheen Reeyad",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=72340000"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/56/Rangabala_Chowdhury%27s_grave%2C_Beas_Kund_%2801%29.jpg",
      "title": "Rangabala Chowdhury's grave, Beas Kund (01)",
      "credit": "Moheen Reeyad",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=72339999"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4e/Morning_beas_kund_trek.jpg",
      "title": "Morning beas kund trek",
      "credit": "Gxyd",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=53112874"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Unknown_graves%2C_Beas_Kund_%2802%29.jpg",
      "title": "Unknown graves, Beas Kund (02)",
      "credit": "Moheen Reeyad",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=72339998"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/19/Beas_kund_rohtang.jpg",
      "title": "Beas kund rohtang",
      "credit": "Thakurveerpalsara",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=145544974"
    }
  ],
  "triund": [
    {
      "url": "https://live.staticflickr.com/8406/8680904492_7f53b18f36_b.jpg",
      "title": "Valley above Triund",
      "credit": "Jace",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/41894175704@N01/8680904492"
    },
    {
      "url": "https://live.staticflickr.com/8385/8680903208_aa3997b2e8_b.jpg",
      "title": "Five towns in one view from Triund",
      "credit": "Jace",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/41894175704@N01/8680903208"
    },
    {
      "url": "https://live.staticflickr.com/8545/8679784957_b15c639139_b.jpg",
      "title": "Triund trek route",
      "credit": "Jace",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/41894175704@N01/8679784957"
    },
    {
      "url": "https://live.staticflickr.com/8534/8679793911_500da1f29c_b.jpg",
      "title": "Snowball fights above Triund",
      "credit": "Jace",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/41894175704@N01/8679793911"
    },
    {
      "url": "https://live.staticflickr.com/8392/8680900740_9f3cc6557f_b.jpg",
      "title": "Triund sunrise over the Dhauladhars",
      "credit": "Jace",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/41894175704@N01/8680900740"
    },
    {
      "url": "https://live.staticflickr.com/8265/8679787277_45a57a96c6_b.jpg",
      "title": "View from Triund",
      "credit": "Jace",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/41894175704@N01/8679787277"
    }
  ],
  "kareri-lake": [
    {
      "url": "https://live.staticflickr.com/2945/15283067688_b0079453a4_b.jpg",
      "title": "Kareri lake and surroundings",
      "credit": "blackfog",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/36853543@N00/15283067688"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/26/Kareri_Lake.JPG",
      "title": "Kareri Lake",
      "credit": "Shalabh (talk)",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=156986448"
    },
    {
      "url": "https://live.staticflickr.com/65535/48101511846_811a41ddf2_b.jpg",
      "title": "Kareri lake campsite, Himachal Pradesh",
      "credit": "tanaykibe",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/152280753@N05/48101511846"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/79/Frozen_Kareri_Lake.jpg",
      "title": "Frozen Kareri Lake",
      "credit": "Lotia57755",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=122845279"
    },
    {
      "url": "https://live.staticflickr.com/65535/48106950927_0a9606c005_b.jpg",
      "title": "Halfway to Kareri lake, Himachal Pradesh",
      "credit": "tanaykibe",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "http://www.flickr.com/photos/152280753@N05/48106950927"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/3/35/Kareri_Lake_%28Kumarwah_Lake%29.jpg",
      "title": "Kareri Lake (Kumarwah Lake)",
      "credit": "Tanvi.sharmaaa",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=185131287"
    }
  ],
  "indrahar-pass": [
    {
      "url": "https://live.staticflickr.com/5829/22356846090_1f90de803a_b.jpg",
      "title": "Looking up to the Indrahar Pass",
      "credit": "blackfog",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/36853543@N00/22356846090"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/20/Looking_up_to_the_Indrahar_Pass_%2822356846090%29.jpg",
      "title": "Looking up to the Indrahar Pass (22356846090)",
      "credit": "Ashish Gupta from Noida, India",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=58857425"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/df/Dhauladhar_Range_%28indrahar_pass%29_view_from_snow_line_point.jpg",
      "title": "Dhauladhar Range (indrahar pass) view from snow line point",
      "credit": "Vivek machra",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=60067705"
    },
    {
      "url": "https://live.staticflickr.com/3/4558218_ada3d4bb83_b.jpg",
      "title": "top of the pass",
      "credit": "rouadec",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/83889980@N00/4558218"
    },
    {
      "url": "https://live.staticflickr.com/7534/16284226341_5e35a1fac7_b.jpg",
      "title": "Looking down at the Laka Got",
      "credit": "blackfog",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/36853543@N00/16284226341"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/5b/Ridge_line_of_Dhauladhar_Range_01.jpg",
      "title": "Ridge line of Dhauladhar Range 01",
      "credit": "Vivek machra",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=60067702"
    }
  ],
  "serolsar-lake-jalori": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/fd/Serolsar_Lake%2C_Jalori_Pass.jpg",
      "title": "Serolsar Lake, Jalori Pass",
      "credit": "Narender moun",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=119104490"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Serolsar_Lake.jpg",
      "title": "Serolsar Lake",
      "credit": "Sukhjiwan Singh",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=139547390"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Serolsar_Lake_2.jpg",
      "title": "Serolsar Lake 2",
      "credit": "Sukhjiwan Singh",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=139547509"
    },
    {
      "url": "https://live.staticflickr.com/3366/3518404884_bee367378d_b.jpg",
      "title": "Youngest Mountain Range in the World",
      "credit": "www.beontheroad.com",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/10208972@N04/3518404884"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/0f/A_Spectacular_view_of_the_Himachal_Valley.jpg",
      "title": "A Spectacular view of the Himachal Valley",
      "credit": "Prabhmeet Singh",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49775109"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/70/Jalori_pass%2C_UNESCO_world_Heritage_site.jpg",
      "title": "Jalori pass, UNESCO world Heritage site",
      "credit": "Manish57335",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=59831303"
    }
  ],
  "nag-tibba": [
    {
      "url": "https://live.staticflickr.com/5128/5283900561_eeed8af27a_b.jpg",
      "title": "Nag Tibba from Lal Tibba",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/5283900561"
    },
    {
      "url": "https://live.staticflickr.com/7508/16231005185_8dc859666f_b.jpg",
      "title": "Nag Tibba jhandi",
      "credit": "blackfog",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/36853543@N00/16231005185"
    },
    {
      "url": "https://live.staticflickr.com/5081/5284625094_46905b1423_b.jpg",
      "title": "Bear Hill and Nag Tibba",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/5284625094"
    },
    {
      "url": "https://live.staticflickr.com/7519/15632227134_72e9863d71_b.jpg",
      "title": "Panorama of camping ground from above the Nag Tibba temple",
      "credit": "blackfog",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/36853543@N00/15632227134"
    },
    {
      "url": "https://live.staticflickr.com/5009/5275868014_1db2b5bebf_b.jpg",
      "title": "Nag Tibba Ridge",
      "credit": "paulhami",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/8306673@N02/5275868014"
    },
    {
      "url": "https://live.staticflickr.com/7531/16255927315_fedc94c483_b.jpg",
      "title": "Motorable road covering some part of the Nag Tibba trail",
      "credit": "blackfog",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/36853543@N00/16255927315"
    }
  ],
  "tadiandamol": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Tadiandamol_Trek_25Aug_Pic_0_View_From_Top.jpg",
      "title": "Tadiandamol Trek 25Aug Pic 0 View From Top",
      "credit": "Navi guy",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=136568715"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Tadiandamol_landscape_-_vrvkbgmtmk1024_%28478%29.jpg",
      "title": "Tadiandamol landscape - vrvkbgmtmk1024 (478)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=177334089"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/Carex_baccans_at_Tadiandamol_-_vrvkbgmtmk1024_%281%29.jpg",
      "title": "Carex baccans at Tadiandamol - vrvkbgmtmk1024 (1)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=177304698"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Athyma_selenophora_-_Staff_Sergeant_female_at_Tadiandamol_-_vrvkbgmtmk1024_%281%29.jpg",
      "title": "Athyma selenophora - Staff Sergeant female at Tadiandamol - vrvkbgmtmk1024 (1)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=177307544"
    },
    {
      "url": "https://live.staticflickr.com/831/39926721220_435fdcb72d_b.jpg",
      "title": "Tadiandamol Hills",
      "credit": "Hari K Patibanda",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/34176693@N06/39926721220"
    }
  ],
  "brahmagiri": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Brahmagiri_Peak.jpg",
      "title": "Brahmagiri Peak",
      "credit": "The MH15",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=60338927"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Thirunelli_to_Brahmagiri_Peak_trekking_-_40498kgb25_%281221%29.jpg",
      "title": "Thirunelli to Brahmagiri Peak trekking - 40498kgb25 (1221)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=178874292"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/06/Thirunelli_to_Brahmagiri_Peak_trekking_-_40498kgb25_%2832%29.jpg",
      "title": "Thirunelli to Brahmagiri Peak trekking - 40498kgb25 (32)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=178877965"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/24/Thirunelli_to_Brahmagiri_Peak_trekking_-_40498kgb25_%281237%29.jpg",
      "title": "Thirunelli to Brahmagiri Peak trekking - 40498kgb25 (1237)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=178874484"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Thirunelli_to_Brahmagiri_Peak_trekking_-_40498kgb25_%28280%29.jpg",
      "title": "Thirunelli to Brahmagiri Peak trekking - 40498kgb25 (280)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=178877408"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/21/Thirunelli_to_Brahmagiri_Peak_trekking_-_40498kgb25_%281209%29.jpg",
      "title": "Thirunelli to Brahmagiri Peak trekking - 40498kgb25 (1209)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=178874112"
    }
  ],
  "david-scott-trail": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4a/David_Scott_Trail.jpg",
      "title": "David Scott Trail",
      "credit": "Wann Majaw",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=145873132"
    },
    {
      "url": "https://live.staticflickr.com/8007/7316743930_916fbd623a_b.jpg",
      "title": "David and the Joshua Tree",
      "credit": "daveynin",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/44124370018@N01/7316743930"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/0b/S-2021_N_1_GeminiNorth_2023-11-03_average_stack_annotated.png",
      "title": "S-2021 N 1 GeminiNorth 2023-11-03 average stack annotated",
      "credit": "Images stacked & processed by Nrco0e. Original frames were taken by Scott S. She",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=169262135"
    },
    {
      "url": "https://live.staticflickr.com/3832/11128922186_82d7b38e64_b.jpg",
      "title": "Applegate Trail, Mud Meadow Marker",
      "credit": "Ken Lund",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/75683070@N00/11128922186"
    },
    {
      "url": "https://live.staticflickr.com/7100/7337427972_8b3a57f73b_b.jpg",
      "title": "Ribbon cutting at the Clyburn Hollow Trail Loop",
      "credit": "vastateparksstaff",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/37922399@N05/7337427972"
    },
    {
      "url": "https://live.staticflickr.com/65535/51773690275_faa842452a_b.jpg",
      "title": "My 25 photos chosen for 2021",
      "credit": "daveynin",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/44124370018@N01/51773690275"
    }
  ],
  "miyar-valley": [
    {
      "url": "https://live.staticflickr.com/3205/3124437046_2d1acb4968.jpg",
      "title": "rohtang pass, lahaul",
      "credit": "nevil zaveri (thank you for 20+M views:)",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/43109416@N00/3124437046"
    },
    {
      "url": "https://live.staticflickr.com/3266/3116143340_e240d4efc3_b.jpg",
      "title": "drizzling in trans-himalaya - 360° panorama, losar spiti",
      "credit": "nevil zaveri (thank you for 20+M views:)",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/43109416@N00/3116143340"
    },
    {
      "url": "https://live.staticflickr.com/3240/3135509444_bbd8333cee_b.jpg",
      "title": "halt, gramphu",
      "credit": "nevil zaveri (thank you for 20+M views:)",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/43109416@N00/3135509444"
    },
    {
      "url": "https://live.staticflickr.com/65535/48990390468_4e2b8dd1ac_b.jpg",
      "title": "Markha River",
      "credit": "Chris Hunkeler",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/14913305@N00/48990390468"
    },
    {
      "url": "https://live.staticflickr.com/3182/3116143336_5ef983abb8_b.jpg",
      "title": "trans-himalaya - 180° panorama, gete spiti",
      "credit": "nevil zaveri (thank you for 20+M views:)",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/43109416@N00/3116143336"
    },
    {
      "url": "https://live.staticflickr.com/3116/3131070346_6f19256879.jpg",
      "title": "close to heaven - closer to hell, manali",
      "credit": "nevil zaveri (thank you for 20+M views:)",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/43109416@N00/3131070346"
    }
  ],
  "kang-la-pass": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b5/Kongmaru_La_Pass_View_%2849043449806%29.jpg",
      "title": "Kongmaru La Pass View (49043449806)",
      "credit": "Chris Hunkeler from Carlsbad, California, USA",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=99909474"
    }
  ],
  "kalindi-khal": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Kalindi_khal_trekking_%282015%29%2C_Uttarkashi_district%2C_Garhwal_division%2C_Uttarakhand%2C_India_a0-DSC00112.jpg",
      "title": "Kalindi khal trekking (2015), Uttarkashi district, Garhwal division, Uttarakhand, India a0-DSC00112",
      "credit": "Dibendu Nandi",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=46762301"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Kalindi_khal_trekking_%282015%29%2C_Uttarkashi_district%2C_Garhwal_division%2C_Uttarakhand%2C_India_a6-IMG_0572.jpg",
      "title": "Kalindi khal trekking (2015), Uttarkashi district, Garhwal division, Uttarakhand, India a6-IMG 0572",
      "credit": "DipankarSen68",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=48922894"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Kalindi_khal_trekking_%282015%29%2C_Uttarkashi_district%2C_Garhwal_division%2C_Uttarakhand%2C_India_a6-IMG_0566.jpg",
      "title": "Kalindi khal trekking (2015), Uttarkashi district, Garhwal division, Uttarakhand, India a6-IMG 0566",
      "credit": "DipankarSen68",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=48922900"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Kalindi_khal_trekking_%282015%29%2C_Uttarkashi_district%2C_Garhwal_division%2C_Uttarakhand%2C_India_a5-IMG_2692.jpg",
      "title": "Kalindi khal trekking (2015), Uttarkashi district, Garhwal division, Uttarakhand, India a5-IMG 2692",
      "credit": "Asish Das75",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=46764262"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Kalindi_khal_trekking_%282015%29%2C_Uttarkashi_district%2C_Garhwal_division%2C_Uttarakhand%2C_India_a4-IMG_2688.jpg",
      "title": "Kalindi khal trekking (2015), Uttarkashi district, Garhwal division, Uttarakhand, India a4-IMG 2688",
      "credit": "Asish Das75",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=46764260"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/47/Kalindi_khal_trekking_%282015%29%2C_Uttarkashi_district%2C_Garhwal_division%2C_Uttarakhand%2C_India_a6-IMG_0574.jpg",
      "title": "Kalindi khal trekking (2015), Uttarkashi district, Garhwal division, Uttarakhand, India a6-IMG 0574",
      "credit": "DipankarSen68",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=48922892"
    }
  ],
  "darcha-lamayuru": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/81/Zanskar-Animation-554x554.gif",
      "title": "Zanskar-Animation-554x554",
      "credit": "BasinField",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=25020628"
    },
    {
      "url": "https://live.staticflickr.com/65535/48990390468_4e2b8dd1ac_b.jpg",
      "title": "Markha River",
      "credit": "Chris Hunkeler",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/14913305@N00/48990390468"
    },
    {
      "url": "https://live.staticflickr.com/65535/48991138922_ce053dcaa5_b.jpg",
      "title": "Markha River and Nearby Mountains",
      "credit": "Chris Hunkeler",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/14913305@N00/48991138922"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/06/Padum_Road_Shingo_La_Zanskar_Oct22_A7C_03574.jpg",
      "title": "Padum Road Shingo La Zanskar Oct22 A7C 03574",
      "credit": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=124573135"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Alien_Territory%2C_Ganda_La_Pass%2C_Ladakh%2C_Stok_area.jpg",
      "title": "Alien Territory, Ganda La Pass, Ladakh, Stok area",
      "credit": "Prateek Sharma",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49599384"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Bikers_Shingo_La_Ri_Zanskar_Lahaul_Oct22_A7C_03541.jpg",
      "title": "Bikers Shingo La Ri Zanskar Lahaul Oct22 A7C 03541",
      "credit": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=124573392"
    }
  ],
  "bailey-trail": [
    {
      "url": "https://live.staticflickr.com/117/290569223_286b7be725_m.jpg",
      "title": "North Ridge Trail @ Sky Meadows State Park",
      "credit": "DCist",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/99294638@N00/290569223"
    }
  ],
  "dzukou-valley": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/44/Breathtaking_beauty_of_Dzukou_Valley_in_Manipur-Nagaland_border_%28edit%29.jpg",
      "title": "Breathtaking beauty of Dzukou Valley in Manipur-Nagaland border (edit)",
      "credit": "Original: Samudra Bikash Hazarika Derivative work: UnpetitproleX",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=167262514"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/86/The_breathtaking_beauty_of_the_Dzukou_Valley.jpg",
      "title": "The breathtaking beauty of the Dzukou Valley",
      "credit": "Inu Etc",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=124615175"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/94/Dzukou_valley_in_the_Nagaland-Manipur_border.jpg",
      "title": "Dzukou valley in the Nagaland-Manipur border",
      "credit": "SeethaG",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49636892"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/da/Inu_Etc_in_Dzukou_Valley%2C_Nagaland.jpg",
      "title": "Inu Etc in Dzukou Valley, Nagaland",
      "credit": "Inu Etc",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=148727260"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Breathtaking_beauty_of_Dzukou_Valley_in_Manipur-Nagaland_border.jpg",
      "title": "Breathtaking beauty of Dzukou Valley in Manipur-Nagaland border",
      "credit": "Samudra bikash hazarika",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=60542442"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/d7/The_Dzukou_Valley.JPG",
      "title": "The Dzukou Valley",
      "credit": "Mongyamba",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=4295809"
    }
  ],
  "kudremukh": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/14/Kudremukh_TheHorseFace.JPG",
      "title": "Kudremukh TheHorseFace",
      "credit": "Wind4wings",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=5637190"
    },
    {
      "url": "https://live.staticflickr.com/2732/4194181101_b7a77cf44b_b.jpg",
      "title": "Sunny side",
      "credit": "h0lydevil",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45516485@N00/4194181101"
    },
    {
      "url": "https://live.staticflickr.com/2553/4194179705_2f0139d0d7_b.jpg",
      "title": "Stream",
      "credit": "h0lydevil",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45516485@N00/4194179705"
    },
    {
      "url": "https://live.staticflickr.com/2565/4194936392_b7ea463cf7_b.jpg",
      "title": "Grass + Shadow",
      "credit": "h0lydevil",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45516485@N00/4194936392"
    },
    {
      "url": "https://live.staticflickr.com/2690/4194936710_c4994e6c42_b.jpg",
      "title": "Rest",
      "credit": "h0lydevil",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45516485@N00/4194936710"
    },
    {
      "url": "https://live.staticflickr.com/2495/4194180835_8ba7f34e30_b.jpg",
      "title": ":)",
      "credit": "h0lydevil",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45516485@N00/4194180835"
    }
  ],
  "kumara-parvatha": [
    {
      "url": "https://live.staticflickr.com/2077/2121495157_6e338335ed_b.jpg",
      "title": "Kumara Parvatha Trek",
      "credit": "bishii",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/9976253@N05/2121495157"
    },
    {
      "url": "https://live.staticflickr.com/4064/4308496674_3a87075d91_b.jpg",
      "title": "Bheemana Bande- kumara parvatha",
      "credit": "Neon-Clix",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45099860@N05/4308496674"
    },
    {
      "url": "https://live.staticflickr.com/4050/4308496064_71ed418244_b.jpg",
      "title": "Beautiful Sunset - Bhattara mane- kumara parvatha",
      "credit": "Neon-Clix",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/45099860@N05/4308496064"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8e/Final_stretch_of_Pushpagiri_Karnataka_India.jpg",
      "title": "Final stretch of Pushpagiri Karnataka India",
      "credit": "Photos Worldwide",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104610822"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1a/Trek_Pushpagiri_Karnataka_India.jpg",
      "title": "Trek Pushpagiri Karnataka India",
      "credit": "Photos Worldwide",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104610825"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tents_on_a_view_point_in_Pushpagiri_wildlife_sanctuary.jpg",
      "title": "Tents on a view point in Pushpagiri wildlife sanctuary",
      "credit": "psubhashish",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=32050408"
    }
  ],
  "gangabal-lakes": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/cb/Horse_riding_near_Gangbal_Lake.JPG",
      "title": "Horse riding near Gangbal Lake",
      "credit": "Owais Khursheed",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=37608583"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/a5/Fishes_of_Gangbal_Lake.JPG",
      "title": "Fishes of Gangbal Lake",
      "credit": "Owais Khursheed",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=37176091"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/7f/Trekking_near_Gangbal_Lake.jpg",
      "title": "Trekking near Gangbal Lake",
      "credit": "Taabishm2",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=62381707"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4c/Gangbal_Lake%2C_Ganderbal.JPG",
      "title": "Gangbal Lake, Ganderbal",
      "credit": "Owais Khursheed",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=37176083"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/af/GangbalPanorama1.jpg",
      "title": "GangbalPanorama1",
      "credit": "Mohamad Talib Bhat",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=78150286"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Gangbal%2C_Kashmir.jpg",
      "title": "Gangbal, Kashmir",
      "credit": "Romesh Bhattacharji",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=59472035"
    }
  ],
  "tirthan-valley": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Trekking_Bridge.jpg",
      "title": "Trekking Bridge",
      "credit": "Ankitwadhwa10",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49827519"
    },
    {
      "url": "https://live.staticflickr.com/65535/52816325110_a51cef29fd_b.jpg",
      "title": "Smoke envelopes Tirthan Valley",
      "credit": "Nagarjun",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/64924693@N00/52816325110"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/05/Welcome_Gate_at_Larji_for_Sainj_and_Tirthan_Valleys%2C_Kullu_District%2C_Himachal_Pradesh.jpg",
      "title": "Welcome Gate at Larji for Sainj and Tirthan Valleys, Kullu District, Himachal Pradesh",
      "credit": "Rajani Gairshail",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=184416943"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/94/Tirthan_River_Tirthan_Valley_DSC00968.jpg",
      "title": "Tirthan River Tirthan Valley DSC00968",
      "credit": "Debashritaiitmandi",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=103271417"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Stone_arrangement_Tirthan_valley_DSC00755.jpg",
      "title": "Stone arrangement Tirthan valley DSC00755",
      "credit": "Debashritaiitmandi",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=103269812"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8c/Cornus_capitata%2C_Tirthan_Valley%2C_Kullu_District%2C_Himachal_Pradesh_%28%E0%A4%AB%E0%A4%BE%E0%A4%97%E0%A5%81%29.jpg",
      "title": "Cornus capitata, Tirthan Valley, Kullu District, Himachal Pradesh (फागु)",
      "credit": "Ramwik",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49774485"
    }
  ],
  "phawngpui": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Pin-striped_Tit-babbler_Macronus_gularis_by_Dr._Raju_Kasambe_DSC_5961_%2865%29.jpg",
      "title": "Pin-striped Tit-babbler Macronus gularis by Dr. Raju Kasambe DSC 5961 (65)",
      "credit": "Dr. Raju Kasambe",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65219144"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Phawngpui_national_park.jpg",
      "title": "Phawngpui national park",
      "credit": "Garima Singh",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49328615"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/53/Pin-striped_Tit-babbler_Macronus_gularis_by_Dr._Raju_Kasambe_%282%29.jpg",
      "title": "Pin-striped Tit-babbler Macronus gularis by Dr. Raju Kasambe (2)",
      "credit": "Dr. Raju Kasambe",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65219139"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/21/Pin-striped_Tit-babbler_Macronus_gularis_by_Dr._Raju_Kasambe.jpg",
      "title": "Pin-striped Tit-babbler Macronus gularis by Dr. Raju Kasambe",
      "credit": "Dr. Raju Kasambe",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65219142"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Pin-striped_Tit-babbler_Macronus_gularis_by_Dr._Raju_Kasambe_%2845%29.jpg",
      "title": "Pin-striped Tit-babbler Macronus gularis by Dr. Raju Kasambe (45)",
      "credit": "Dr. Raju Kasambe",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65219148"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/91/Mrs._Gould%27s_Sunbird_Aethopyga_gouldiae_Male_by_Dr._Raju_Kasambe_DSC_1567_%2811%29.jpg",
      "title": "Mrs. Gould's Sunbird Aethopyga gouldiae Male by Dr. Raju Kasambe DSC 1567 (11)",
      "credit": "Dr. Raju Kasambe",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65219140"
    }
  ],
  "chembra-peak": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Chembra_Peak_Trek_starting_point.jpg",
      "title": "Chembra Peak Trek starting point",
      "credit": "Karkiabhijeet",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49800525"
    },
    {
      "url": "https://live.staticflickr.com/4120/4923682803_aef7b798d2_b.jpg",
      "title": "Trekking to Chembra Peak",
      "credit": "www.beontheroad.com",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/10208972@N04/4923682803"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Chembra_Peak_Heart_Lake.jpg",
      "title": "Chembra Peak Heart Lake",
      "credit": "Ravi Dwivedi",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=136756781"
    },
    {
      "url": "https://live.staticflickr.com/1042/4608525570_ee1b87c5d8_b.jpg",
      "title": "along the way",
      "credit": "friedwater",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/10185281@N05/4608525570"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Chembra_Peak_%2C_Wayanad.jpg",
      "title": "Chembra Peak , Wayanad",
      "credit": "Robin S Kishore",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49669271"
    }
  ],
  "kedarkantha": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Sun_Rise_View_from_Kedarkantha_Summit.jpg",
      "title": "Sun Rise View from Kedarkantha Summit",
      "credit": "Atulbhats",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65604527"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Himalayas_from_Kedarkantha_Summit.jpg",
      "title": "Himalayas from Kedarkantha Summit",
      "credit": "Atulbhats",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=65604589"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Kedarkantha_summit_12500ft.jpg",
      "title": "Kedarkantha summit 12500ft",
      "credit": "Pradhumn04",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=137558123"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/07/Summit_of_Kedarkantha.jpg",
      "title": "Summit of Kedarkantha",
      "credit": "Lawanoopyadav",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=167649103"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/3/37/Blocks_at_Summit.jpg",
      "title": "Blocks at Summit",
      "credit": "Lawanoopyadav",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=167649104"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/cd/Kedarkantha.jpg",
      "title": "Kedarkantha",
      "credit": "rakesh kumar",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=59557297"
    }
  ],
  "valley-of-flowers": [
    {
      "url": "https://live.staticflickr.com/4084/4951216953_abe3ed7899_b.jpg",
      "title": "valley of flowers",
      "credit": "aloshbennett",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/13203757@N00/4951216953"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/5b/%22Flowers_Blossom_at_Valley_of_Flowers_Chamoli%2C_India%22_58.jpg",
      "title": "'Flowers Blossom at Valley of Flowers Chamoli, India' 58",
      "credit": "Naresh Chandra",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=60440392"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/48/Acer_acuminatum_on_way_from_Govindghat_to_Gangria_at_Valley_of_Flowers_National_Park_-_during_LGFC_-_VOF_2019_%281%29.jpg",
      "title": "Acer acuminatum on way from Govindghat to Gangria at Valley of Flowers National Park - during LGFC - VOF 2019 (1)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=85813908"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/52/Valley_of_flowers_National_Park_22.JPG",
      "title": "Valley of flowers National Park 22",
      "credit": "Guptaele",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=35662004"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Argynnis_kamala_-_Common_Silverstripe_from_Valley_of_Flowers_National_Park_-_during_LGFC_-_VOF_2019_%2847%29.jpg",
      "title": "Argynnis kamala - Common Silverstripe from Valley of Flowers National Park - during LGFC - VOF 2019 (47)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=88892116"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Salix_denticulata_on_way_from_Govindghat_to_Gangria_at_Valley_of_Flowers_National_Park_-_during_LGFC_-_VOF_2019_%283%29.jpg",
      "title": "Salix denticulata on way from Govindghat to Gangria at Valley of Flowers National Park - during LGFC - VOF 2019 (3)",
      "credit": "Vinayaraj",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=85815761"
    }
  ],
  "roopkund": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/ad/Mysterious_Skeleton_Roopkund_Lake_Trek_route-10.jpg",
      "title": "Mysterious Skeleton Roopkund Lake Trek route-10",
      "credit": "Daniel Romanson",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104337427"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e1/Mysterious_Skeleton_Roopkund_Lake_Trek_route-8.jpg",
      "title": "Mysterious Skeleton Roopkund Lake Trek route-8",
      "credit": "Daniel Romanson",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104337426"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/72/Mysterious_Skeleton_Roopkund_Lake_Trek_route-1.jpg",
      "title": "Mysterious Skeleton Roopkund Lake Trek route-1",
      "credit": "Daniel Romanson",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104337415"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Mysterious_Skeleton_Roopkund_Lake_Trek_route-3.jpg",
      "title": "Mysterious Skeleton Roopkund Lake Trek route-3",
      "credit": "Daniel Romanson",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104337416"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/76/Mysterious_Skeleton_Roopkund_Lake_Trek_route-9.jpg",
      "title": "Mysterious Skeleton Roopkund Lake Trek route-9",
      "credit": "Daniel Romanson",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104337429"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Mysterious_Skeleton_Roopkund_Lake_Trek_route-5.jpg",
      "title": "Mysterious Skeleton Roopkund Lake Trek route-5",
      "credit": "Daniel Romanson",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=104337422"
    }
  ],
  "har-ki-dun": [
    {
      "url": "https://live.staticflickr.com/570/21018687911_75bbba0a17_b.jpg",
      "title": "Har Ki Dun Valley View",
      "credit": "curious.eagle",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/135745674@N06/21018687911"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/83/Har_Ki_Dun_Valley_View_%2821018687911%29.jpg",
      "title": "Har Ki Dun Valley View (21018687911)",
      "credit": "Curious Eagle",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=105218287"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/96/Har_Ki_Dun_Valley_View_%2820823461470%29.jpg",
      "title": "Har Ki Dun Valley View (20823461470)",
      "credit": "Curious Eagle",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=105218300"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Har_Ki_Dun.jpg",
      "title": "Har Ki Dun",
      "credit": "Metanish",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=35106967"
    },
    {
      "url": "https://live.staticflickr.com/691/21753624775_d029f84f1d_b.jpg",
      "title": "s__IMG_8818_pp-goint-to-Taluka-Sankri-at-the-center",
      "credit": "curious.eagle",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/135745674@N06/21753624775"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Entering_Har_Ki_Dun.JPG",
      "title": "Entering Har Ki Dun",
      "credit": "Omkar",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=43781173"
    }
  ],
  "kuari-pass": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Mountain_Peak.jpg",
      "title": "Mountain Peak",
      "credit": "Hari4025",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49406464"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1e/View_of_Himalayan_Peaks_Chaukhamba%2C_Neelkanth%2C_Kamet%2C_Mana%2C_Gori_Parbat_and_Hathi_Parbat_from_Kuari_Pass.jpg",
      "title": "View of Himalayan Peaks Chaukhamba, Neelkanth, Kamet, Mana, Gori Parbat and Hathi Parbat from Kuari Pass",
      "credit": "Bidhubhusan Patel",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49770099"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/3/35/Hathi_Parbat_from_Gorson_Bugyal.jpg",
      "title": "Hathi Parbat from Gorson Bugyal",
      "credit": "Sumodm",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=88009325"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/ac/Gorson_Bugyal.jpg",
      "title": "Gorson Bugyal",
      "credit": "Vaibhav78545",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=98579122"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Nilgiri_Parbat_From_Gorson_Bugyal.jpg",
      "title": "Nilgiri Parbat From Gorson Bugyal",
      "credit": "Sumodm",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=88008679"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8f/Nanda_Devi_Parvat.jpg",
      "title": "Nanda Devi Parvat",
      "credit": "Catherine Lunaa",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=131772494"
    }
  ],
  "dayara-bugyal": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/3/39/Dayara_Bugyal.jpg",
      "title": "Dayara Bugyal",
      "credit": "Vaibhav78545",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=98647548"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/29/Dayara_Bugyal_3.jpg",
      "title": "Dayara Bugyal 3",
      "credit": "Vaibhav78545",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=98647549"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/56/Dayara_Bugyal_2.jpg",
      "title": "Dayara Bugyal 2",
      "credit": "Vaibhav78545",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=98647551"
    },
    {
      "url": "https://live.staticflickr.com/65535/49011176693_f89f7d79e8_b.jpg",
      "title": "Dayara Bugyal Trek",
      "credit": "Mike Prince",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/70804987@N00/49011176693"
    }
  ],
  "gaumukh-tapovan": [
    {
      "url": "https://live.staticflickr.com/8587/16031252363_3caea85de8_b.jpg",
      "title": "Streets of himalayas",
      "credit": "gunny_2008",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/24536856@N03/16031252363"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/ed/Gaumukh_Gangotri_glacier.jpg",
      "title": "Gaumukh Gangotri glacier",
      "credit": "Atarax42",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=5336101"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b9/Two_Cubs_playing_with_Mother_Himalayan_Brown_Bear.JPG",
      "title": "Two Cubs playing with Mother Himalayan Brown Bear",
      "credit": "Ruchir Patel",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=40814146"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Himalayan_Brown_Bear_With_Cubs.JPG",
      "title": "Himalayan Brown Bear With Cubs",
      "credit": "Ruchir Patel",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=40814145"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Gangotri_glacier_snout.jpg",
      "title": "Gangotri glacier snout",
      "credit": "gbSk at Flickr",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=15284184"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Gaumukh_Glacier.jpg",
      "title": "Gaumukh Glacier",
      "credit": "ShekharRawat07",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49577174"
    }
  ],
  "brahmatal": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Panorama_of_Garhwal_Peaks_as_seen_from_Brahmatal_trek.jpg",
      "title": "Panorama of Garhwal Peaks as seen from Brahmatal trek",
      "credit": "Yash Soorma",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=98966223"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/40/Brahmatal_%28cropped%29.jpg",
      "title": "Brahmatal (cropped)",
      "credit": "Arijit95jitu",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=182345596"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/2/27/Brahmatal.jpg",
      "title": "Brahmatal",
      "credit": "Arijit95jitu",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=72894544"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Brahmatal_camp_site.jpg",
      "title": "Brahmatal camp site",
      "credit": "Arijit95jitu",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=72894251"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Bekaltal.jpg",
      "title": "Bekaltal",
      "credit": "Himani611",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=60318255"
    }
  ],
  "bali-pass": [
    {
      "url": "https://live.staticflickr.com/4916/46049415482_87f25a578a_b.jpg",
      "title": "Once again inspired by Liesel Hlista of Nat Geo, I had booked a helicopter flight over the volcano",
      "credit": "shankar s.",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/77742560@N06/46049415482"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/ee/Tarakund_Mahadev-5.jpg",
      "title": "Tarakund Mahadev-5",
      "credit": "Prakash Chandra Godiyal",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=115406513"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/55/Tarakund_Mahadev-3.jpg",
      "title": "Tarakund Mahadev-3",
      "credit": "Prakash Chandra Godiyal",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=115406510"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/3/3b/Tarakund_Mahadev-4.jpg",
      "title": "Tarakund Mahadev-4",
      "credit": "Prakash Chandra Godiyal",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=115406511"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/77/Tarakund_Mahadev-1.jpg",
      "title": "Tarakund Mahadev-1",
      "credit": "Prakash Chandra Godiyal",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=115406507"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/07/Tarakund_Mahadev-6.jpg",
      "title": "Tarakund Mahadev-6",
      "credit": "Prakash Chandra Godiyal",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=115406514"
    }
  ],
  "kedartal": [
    {
      "url": "https://live.staticflickr.com/118/264162720_eecaacc5fa.jpg",
      "title": "IMG_1859",
      "credit": "anirbanbiswas_c8",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/25966716@N00/264162720"
    },
    {
      "url": "https://live.staticflickr.com/104/264150202_59ddd18b54.jpg",
      "title": "IMG_1848",
      "credit": "anirbanbiswas_c8",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/25966716@N00/264150202"
    },
    {
      "url": "https://live.staticflickr.com/116/264126717_aa03f6c91f_b.jpg",
      "title": "IMG_1839",
      "credit": "anirbanbiswas_c8",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/25966716@N00/264126717"
    },
    {
      "url": "https://live.staticflickr.com/95/264170217_a5e868e6ec.jpg",
      "title": "IMG_1877",
      "credit": "anirbanbiswas_c8",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/25966716@N00/264170217"
    },
    {
      "url": "https://live.staticflickr.com/111/264174114_dc2bf5448f.jpg",
      "title": "IMG_1879",
      "credit": "anirbanbiswas_c8",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/25966716@N00/264174114"
    },
    {
      "url": "https://live.staticflickr.com/119/264162719_52b84af844.jpg",
      "title": "IMG_1872",
      "credit": "anirbanbiswas_c8",
      "license": "CC BY-SA 2.0",
      "sourceUrl": "https://www.flickr.com/photos/25966716@N00/264162719"
    }
  ],
  "madmaheshwar": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/5/5f/Madhyamaheshwar_Temple%2C_Uttarakhand.JPG",
      "title": "Madhyamaheshwar Temple, Uttarakhand",
      "credit": "Bodhisattwa",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=36374263"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Chaukhamba_from_Madhyamaheshwar_%28Old%29.jpg",
      "title": "Chaukhamba from Madhyamaheshwar (Old)",
      "credit": "Ishwari Rai",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=15507349"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Mt_Mandani_and_Chaukhamba_with_reflection_at_Boodha_Madhyamaheshwar_3500m_Photo_by_Sumita_Roy.jpg",
      "title": "Mt Mandani and Chaukhamba with reflection at Boodha Madhyamaheshwar 3500m Photo by Sumita Roy",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=43376429"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/09/Mount_Mandani_viewed_from_Gaundar_to_Madhyamaheshwar_Trail.JPG",
      "title": "Mount Mandani viewed from Gaundar to Madhyamaheshwar Trail",
      "credit": "Bodhisattwa",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=36365278"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Chaukhamba_at_Boodha_Madhyamaheshwar.jpg",
      "title": "Chaukhamba at Boodha Madhyamaheshwar",
      "credit": "Abhishek.ghosh1984",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49314980"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/b7/Reflection_of_Mount_Mandani_on_the_frozen_taal_at_Buda_Madhyamaheshwar_top.JPG",
      "title": "Reflection of Mount Mandani on the frozen taal at Buda Madhyamaheshwar top",
      "credit": "Bodhisattwa",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=36467084"
    }
  ],
  "pangarchulla": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/87/Pangarchulla_Peak.jpg",
      "title": "Pangarchulla Peak",
      "credit": "ShwethaSulegai",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=67127843"
    }
  ],
  "pindari-glacier": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/PINDARI_GLACIERMAPENGLISH_made_by_Sumita_Roy.png",
      "title": "PINDARI GLACIERMAPENGLISH made by Sumita Roy",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=42800612"
    },
    {
      "url": "https://live.staticflickr.com/8708/17546729696_1b295e8f03_b.jpg",
      "title": "Startrails",
      "credit": "Gaurav.Jetley",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/120278543@N02/17546729696"
    },
    {
      "url": "https://live.staticflickr.com/7682/17573660685_c3e487d8d1_b.jpg",
      "title": "_DSC0118",
      "credit": "Gaurav.Jetley",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/120278543@N02/17573660685"
    },
    {
      "url": "https://live.staticflickr.com/5343/17385867350_4705aea162_b.jpg",
      "title": "_DSC0173",
      "credit": "Gaurav.Jetley",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/120278543@N02/17385867350"
    },
    {
      "url": "https://live.staticflickr.com/8700/17385482308_2490c0a264_b.jpg",
      "title": "_DSC0318",
      "credit": "Gaurav.Jetley",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/120278543@N02/17385482308"
    },
    {
      "url": "https://live.staticflickr.com/5465/17387095429_22740a9e2e_b.jpg",
      "title": "_DSC0175",
      "credit": "Gaurav.Jetley",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/120278543@N02/17387095429"
    }
  ],
  "kafni-glacier": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/PINDARI_GLACIERMAPENGLISH_made_by_Sumita_Roy.png",
      "title": "PINDARI GLACIERMAPENGLISH made by Sumita Roy",
      "credit": "Sumita Roy Dutta",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=42800612"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Kafni_glacier.jpg",
      "title": "Kafni glacier",
      "credit": "Anuragkjain at English Wikipedia",
      "license": "CC BY 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=34162152"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Pindar_river.jpg",
      "title": "Pindar river",
      "credit": "Harshit SR",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=149532414"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Parmelia_pindarensis_D_D_Awasthi_%26_Singh_nmnhbotany_2123964_NMNH-00068960-000001.jpg",
      "title": "Parmelia pindarensis D D Awasthi & Singh nmnhbotany 2123964 NMNH-00068960-000001",
      "credit": "National Museum of Natural History",
      "license": "CC0 1.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=142316060"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/f/f9/Pindari_river_from_Dwali%2C_Uttarakhand%2C_India.jpg",
      "title": "Pindari river from Dwali, Uttarakhand, India",
      "credit": "Yann (talk)",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=16955627"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Bridge_on_the_Pindari_river_near_Dwali%2C_Uttarakhand%2C_India.jpg",
      "title": "Bridge on the Pindari river near Dwali, Uttarakhand, India",
      "credit": "Yann (talk)",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=16963709"
    }
  ],
  "milam-glacier": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/RN015_Vanessa_indica.jpg",
      "title": "RN015 Vanessa indica",
      "credit": "No machine-readable author provided. Nature Loader assumed (based on copyright c",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=732309"
    },
    {
      "url": "https://live.staticflickr.com/217/517612947_e52559252a_b.jpg",
      "title": "Looks to Kill",
      "credit": "feelfree82",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/83407406@N00/517612947"
    },
    {
      "url": "https://live.staticflickr.com/3860/14401853494_7c746ebbe3_b.jpg",
      "title": "Sunrise at Munsiyari",
      "credit": "kg.abhi",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/31518092@N04/14401853494"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Helotidae_Munsiyari.jpg",
      "title": "Helotidae Munsiyari",
      "credit": "Shyamal",
      "license": "CC BY 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=80604250"
    },
    {
      "url": "https://live.staticflickr.com/3901/14547053363_3a5eafc601_b.jpg",
      "title": "Sunrise at Munsiyari - I",
      "credit": "kg.abhi",
      "license": "CC BY 2.0",
      "sourceUrl": "https://www.flickr.com/photos/31518092@N04/14547053363"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Panchchuli_Peaks%2C_near_Munsiyari%2C_Uttarakhand.jpg",
      "title": "Panchchuli Peaks, near Munsiyari, Uttarakhand",
      "credit": "https://www.flickr.com/photos/73109955@N00/",
      "license": "CC BY 2.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=6873418"
    }
  ],
  "khaliya-top": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/45/Fulvous-breasted_Woodpecker_Dendrocopos_macei%2C_Munsiyari%2C_Uttarakhand.jpg",
      "title": "Fulvous-breasted Woodpecker Dendrocopos macei, Munsiyari, Uttarakhand",
      "credit": "kmh4321",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49812489"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/a/a7/Alpine_meadow_Khaliya.jpg",
      "title": "Alpine meadow Khaliya",
      "credit": "Shyamal L.",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49083096"
    }
  ],
  "panchachuli-base-camp": [
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Panchachuli_and_nearby_peaks.jpg",
      "title": "Panchachuli and nearby peaks",
      "credit": "Brindha.nagarajan",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=49792812"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/c/cc/Panchachuli.JPG",
      "title": "Panchachuli",
      "credit": "Spatni2",
      "license": "CC BY-SA 3.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=23928689"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/1/1b/Panchachuli_Pithauragarh.jpg",
      "title": "Panchachuli Pithauragarh",
      "credit": "Rohit Gosain",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=71194110"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/0/01/%22Didihat_Town_and_Panchachuli_peaks_in_the_background.jpg%22.jpg",
      "title": "'Didihat Town and Panchachuli peaks in the background.jpg'",
      "credit": "Khushwant Kafaliya",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=105358064"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/d/dc/Panchachuli_from_Darma_Valley.jpg",
      "title": "Panchachuli from Darma Valley",
      "credit": "Kuldeep vittan",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=90096924"
    },
    {
      "url": "https://upload.wikimedia.org/wikipedia/commons/7/74/Panchachuli_Trek%2C_in_Darma_Valley.jpg",
      "title": "Panchachuli Trek, in Darma Valley",
      "credit": "Kuldeep vittan",
      "license": "CC BY-SA 4.0",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=90097051"
    }
  ],
};
